// AUTO-GENERATED by scripts/port-maquette.mjs from site-maquette/index.html.
// Do not edit by hand. The maquette is the source of truth for questions & options.
// Re-run: node scripts/port-maquette.mjs
import type { LocalizedQuestions } from './prediag';

export const QUESTIONS: LocalizedQuestions = {
  "fr": [
    {
      "q": "Quel est le statut juridique du terrain ?",
      "hint": "Le statut détermine si le terrain est cessible et constructible.",
      "crit": "bloquant",
      "opts": [
        {
          "t": "Titre foncier (immatriculé)",
          "s": "ok"
        },
        {
          "t": "Melk non titré",
          "s": "warn",
          "r": "Faites immatriculer le terrain avant l'achat pour sécuriser la propriété."
        },
        {
          "t": "Collectif / Guich / Habous",
          "s": "bad",
          "r": "Statut souvent inaliénable ou non constructible : vérification juridique impérative."
        },
        {
          "t": "Je ne sais pas",
          "s": "unk",
          "r": "Identifiez le statut foncier en priorité : c'est le socle de tout."
        }
      ]
    },
    {
      "q": "Avez-vous un certificat de propriété de moins de 3 mois ?",
      "hint": "Délivré par la Conservation foncière (ANCFCC).",
      "crit": "bloquant",
      "opts": [
        {
          "t": "Oui",
          "s": "ok"
        },
        {
          "t": "Non",
          "s": "bad",
          "r": "Obtenez un certificat de propriété récent : il révèle le vrai propriétaire et les charges."
        },
        {
          "t": "Je ne sais pas",
          "s": "unk",
          "r": "Procurez-vous un certificat de propriété récent auprès de l'ANCFCC."
        }
      ]
    },
    {
      "q": "Le vendeur est-il bien le propriétaire inscrit (CIN = titre) ?",
      "hint": "Comparez la CIN au nom figurant sur le titre.",
      "crit": "bloquant",
      "opts": [
        {
          "t": "Oui",
          "s": "ok"
        },
        {
          "t": "Non",
          "s": "bad",
          "r": "Identité vendeur ≠ propriétaire : risque majeur de fraude. À bloquer."
        },
        {
          "t": "Je ne sais pas",
          "s": "unk",
          "r": "Vérifiez que le vendeur est le propriétaire inscrit, et toute procuration."
        }
      ]
    },
    {
      "q": "En cas d'indivision/succession, tous les héritiers sont-ils d'accord ?",
      "hint": "Tous les co-indivisaires doivent consentir à la vente.",
      "crit": "bloquant",
      "opts": [
        {
          "t": "Oui, tous d'accord",
          "s": "ok"
        },
        {
          "t": "Non concerné (un seul propriétaire)",
          "s": "ok"
        },
        {
          "t": "Non / partiellement",
          "s": "bad",
          "r": "Sans l'accord de tous les héritiers, la vente est attaquable. À régulariser."
        },
        {
          "t": "Je ne sais pas",
          "s": "unk",
          "r": "Vérifiez l'acte d'hérédité et l'accord de tous les co-indivisaires."
        }
      ]
    },
    {
      "q": "Le terrain est-il libre d'hypothèque, saisie ou opposition ?",
      "hint": "Ces charges apparaissent sur le certificat de propriété.",
      "crit": "eleve",
      "opts": [
        {
          "t": "Oui, libre de toute charge",
          "s": "ok"
        },
        {
          "t": "Non",
          "s": "bad",
          "r": "Faites lever ou purger toute hypothèque/saisie avant l'achat."
        },
        {
          "t": "Je ne sais pas",
          "s": "unk",
          "r": "Vérifiez les inscriptions (hypothèque, saisie, opposition) sur le titre."
        }
      ]
    },
    {
      "q": "Avez-vous la note de renseignements de l'agence urbaine ?",
      "hint": "Elle précise le zonage et les règles de construction.",
      "crit": "bloquant",
      "opts": [
        {
          "t": "Oui",
          "s": "ok"
        },
        {
          "t": "Non",
          "s": "bad",
          "r": "Obtenez la note de renseignements de l'agence urbaine : indispensable."
        },
        {
          "t": "Je ne sais pas",
          "s": "unk",
          "r": "Demandez la note de renseignements d'urbanisme avant tout engagement."
        }
      ]
    },
    {
      "q": "Le terrain est-il classé constructible ?",
      "hint": "Vérifiez le zonage au plan d'aménagement.",
      "crit": "bloquant",
      "opts": [
        {
          "t": "Oui",
          "s": "ok"
        },
        {
          "t": "Non / zone agricole ou verte",
          "s": "bad",
          "r": "Un terrain non constructible ruine le projet. Confirmez le zonage."
        },
        {
          "t": "Je ne sais pas",
          "s": "unk",
          "r": "Confirmez la constructibilité au plan d'aménagement."
        }
      ]
    },
    {
      "q": "Le terrain a-t-il un accès direct à la voie publique ?",
      "hint": "Un terrain enclavé est difficile à exploiter.",
      "crit": "bloquant",
      "opts": [
        {
          "t": "Oui",
          "s": "ok"
        },
        {
          "t": "Non / enclavé",
          "s": "bad",
          "r": "Sécurisez un accès légal : un terrain enclavé bloque le permis."
        },
        {
          "t": "Je ne sais pas",
          "s": "unk",
          "r": "Vérifiez l'existence d'un accès légal à la voie publique."
        }
      ]
    },
    {
      "q": "Le bornage a-t-il été réalisé par un géomètre ?",
      "hint": "Il confirme la surface réelle et les limites.",
      "crit": "eleve",
      "opts": [
        {
          "t": "Oui",
          "s": "ok"
        },
        {
          "t": "Non",
          "s": "bad",
          "r": "Faites borner le terrain : la surface réelle diffère parfois du titre."
        },
        {
          "t": "Je ne sais pas",
          "s": "unk",
          "r": "Prévoyez un bornage par géomètre avant la transaction."
        }
      ]
    },
    {
      "q": "Le paiement passera-t-il par un notaire (et non en espèces) ?",
      "hint": "Le notaire sécurise les fonds et l'acte.",
      "crit": "eleve",
      "opts": [
        {
          "t": "Oui, via notaire",
          "s": "ok"
        },
        {
          "t": "Non / en espèces",
          "s": "bad",
          "r": "Passez par un notaire : le cash expose à la fraude et à une pénalité."
        },
        {
          "t": "Je ne sais pas",
          "s": "unk",
          "r": "Prévoyez un paiement sécurisé via notaire, jamais en espèces."
        }
      ]
    }
  ],
  "ar": [
    {
      "q": "ما هو الوضع القانوني للأرض؟",
      "hint": "الوضع يحدّد ما إذا كانت الأرض قابلة للتفويت والبناء.",
      "crit": "bloquant",
      "opts": [
        {
          "t": "رسم عقاري (محفّظة)",
          "s": "ok"
        },
        {
          "t": "ملك غير محفّظ",
          "s": "warn",
          "r": "قم بتحفيظ الأرض قبل الشراء لتأمين الملكية."
        },
        {
          "t": "جماعية / كيش / حبوس",
          "s": "bad",
          "r": "وضع غالبًا غير قابل للتفويت أو البناء: التحقق القانوني إلزامي."
        },
        {
          "t": "لا أعرف",
          "s": "unk",
          "r": "حدّد الوضع العقاري أولًا: إنه أساس كل شيء."
        }
      ]
    },
    {
      "q": "هل لديك شهادة ملكية أقل من 3 أشهر؟",
      "hint": "تُسلَّم من المحافظة العقارية (ANCFCC).",
      "crit": "bloquant",
      "opts": [
        {
          "t": "نعم",
          "s": "ok"
        },
        {
          "t": "لا",
          "s": "bad",
          "r": "احصل على شهادة ملكية حديثة: تكشف المالك الحقيقي والأعباء."
        },
        {
          "t": "لا أعرف",
          "s": "unk",
          "r": "احصل على شهادة ملكية حديثة من المحافظة العقارية."
        }
      ]
    },
    {
      "q": "هل البائع هو فعلًا المالك المسجَّل (البطاقة الوطنية = الرسم)؟",
      "hint": "قارن البطاقة الوطنية بالاسم المذكور في الرسم.",
      "crit": "bloquant",
      "opts": [
        {
          "t": "نعم",
          "s": "ok"
        },
        {
          "t": "لا",
          "s": "bad",
          "r": "هوية البائع ≠ المالك: خطر احتيال كبير. يجب التوقف."
        },
        {
          "t": "لا أعرف",
          "s": "unk",
          "r": "تحقّق أن البائع هو المالك المسجَّل، وأي وكالة."
        }
      ]
    },
    {
      "q": "في حالة الشياع/الإرث، هل كل الورثة موافقون؟",
      "hint": "يجب أن يوافق جميع الشركاء في الملك على البيع.",
      "crit": "bloquant",
      "opts": [
        {
          "t": "نعم، الجميع موافق",
          "s": "ok"
        },
        {
          "t": "غير معني (مالك واحد)",
          "s": "ok"
        },
        {
          "t": "لا / جزئيًا",
          "s": "bad",
          "r": "دون موافقة كل الورثة، يكون البيع قابلًا للطعن. يجب التسوية."
        },
        {
          "t": "لا أعرف",
          "s": "unk",
          "r": "تحقّق من رسم الإراثة وموافقة جميع الشركاء."
        }
      ]
    },
    {
      "q": "هل الأرض خالية من الرهن أو الحجز أو التعرّض؟",
      "hint": "تظهر هذه الأعباء في شهادة الملكية.",
      "crit": "eleve",
      "opts": [
        {
          "t": "نعم، خالية من كل عبء",
          "s": "ok"
        },
        {
          "t": "لا",
          "s": "bad",
          "r": "ارفع أو طهّر أي رهن/حجز قبل الشراء."
        },
        {
          "t": "لا أعرف",
          "s": "unk",
          "r": "تحقّق من التقييدات (رهن، حجز، تعرّض) على الرسم."
        }
      ]
    },
    {
      "q": "هل لديك مذكّرة معلومات من الوكالة الحضرية؟",
      "hint": "تحدّد التقسيم وقواعد البناء.",
      "crit": "bloquant",
      "opts": [
        {
          "t": "نعم",
          "s": "ok"
        },
        {
          "t": "لا",
          "s": "bad",
          "r": "احصل على مذكّرة المعلومات من الوكالة الحضرية: لا غنى عنها."
        },
        {
          "t": "لا أعرف",
          "s": "unk",
          "r": "اطلب مذكّرة معلومات التعمير قبل أي التزام."
        }
      ]
    },
    {
      "q": "هل الأرض مصنّفة قابلة للبناء؟",
      "hint": "تحقّق من التقسيم في تصميم التهيئة.",
      "crit": "bloquant",
      "opts": [
        {
          "t": "نعم",
          "s": "ok"
        },
        {
          "t": "لا / منطقة فلاحية أو خضراء",
          "s": "bad",
          "r": "أرض غير قابلة للبناء تدمّر المشروع. أكّد التقسيم."
        },
        {
          "t": "لا أعرف",
          "s": "unk",
          "r": "أكّد قابلية البناء في تصميم التهيئة."
        }
      ]
    },
    {
      "q": "هل للأرض منفذ مباشر إلى الطريق العمومي؟",
      "hint": "الأرض المحبوسة صعبة الاستغلال.",
      "crit": "bloquant",
      "opts": [
        {
          "t": "نعم",
          "s": "ok"
        },
        {
          "t": "لا / محبوسة",
          "s": "bad",
          "r": "أمّن منفذًا قانونيًا: الأرض المحبوسة تعرقل الرخصة."
        },
        {
          "t": "لا أعرف",
          "s": "unk",
          "r": "تحقّق من وجود منفذ قانوني إلى الطريق العمومي."
        }
      ]
    },
    {
      "q": "هل أُنجز التحديد من طرف مساح طوبوغرافي؟",
      "hint": "يؤكّد المساحة الحقيقية والحدود.",
      "crit": "eleve",
      "opts": [
        {
          "t": "نعم",
          "s": "ok"
        },
        {
          "t": "لا",
          "s": "bad",
          "r": "قم بتحديد الأرض: المساحة الحقيقية تختلف أحيانًا عن الرسم."
        },
        {
          "t": "لا أعرف",
          "s": "unk",
          "r": "خطّط لتحديد من طرف مساح قبل المعاملة."
        }
      ]
    },
    {
      "q": "هل سيتم الأداء عبر موثّق (وليس نقدًا)؟",
      "hint": "الموثّق يؤمّن الأموال والعقد.",
      "crit": "eleve",
      "opts": [
        {
          "t": "نعم، عبر موثّق",
          "s": "ok"
        },
        {
          "t": "لا / نقدًا",
          "s": "bad",
          "r": "مرّ عبر موثّق: النقد يعرّض للاحتيال ولغرامة."
        },
        {
          "t": "لا أعرف",
          "s": "unk",
          "r": "خطّط لأداء آمن عبر موثّق، وليس نقدًا أبدًا."
        }
      ]
    }
  ],
  "en": [
    {
      "q": "What is the legal status of the land?",
      "hint": "The status determines whether the land can be sold and built on.",
      "crit": "bloquant",
      "opts": [
        {
          "t": "Land title (registered)",
          "s": "ok"
        },
        {
          "t": "Unregistered melk",
          "s": "warn",
          "r": "Register the land before buying to secure ownership."
        },
        {
          "t": "Collective / Guich / Habous",
          "s": "bad",
          "r": "Often inalienable or non-buildable status: legal check is mandatory."
        },
        {
          "t": "I don't know",
          "s": "unk",
          "r": "Identify the land status first: it's the foundation of everything."
        }
      ]
    },
    {
      "q": "Do you have a property certificate less than 3 months old?",
      "hint": "Issued by the Land Registry (ANCFCC).",
      "crit": "bloquant",
      "opts": [
        {
          "t": "Yes",
          "s": "ok"
        },
        {
          "t": "No",
          "s": "bad",
          "r": "Get a recent property certificate: it reveals the true owner and any charges."
        },
        {
          "t": "I don't know",
          "s": "unk",
          "r": "Obtain a recent property certificate from ANCFCC."
        }
      ]
    },
    {
      "q": "Is the seller really the registered owner (ID = title)?",
      "hint": "Compare the ID card to the name on the title.",
      "crit": "bloquant",
      "opts": [
        {
          "t": "Yes",
          "s": "ok"
        },
        {
          "t": "No",
          "s": "bad",
          "r": "Seller ≠ owner: major fraud risk. Stop here."
        },
        {
          "t": "I don't know",
          "s": "unk",
          "r": "Check that the seller is the registered owner, and any power of attorney."
        }
      ]
    },
    {
      "q": "In case of joint ownership/inheritance, do all heirs agree?",
      "hint": "All co-owners must consent to the sale.",
      "crit": "bloquant",
      "opts": [
        {
          "t": "Yes, all agree",
          "s": "ok"
        },
        {
          "t": "Not concerned (single owner)",
          "s": "ok"
        },
        {
          "t": "No / partially",
          "s": "bad",
          "r": "Without all heirs' consent, the sale is challengeable. Must be regularised."
        },
        {
          "t": "I don't know",
          "s": "unk",
          "r": "Check the inheritance deed and all co-owners' consent."
        }
      ]
    },
    {
      "q": "Is the land free of mortgage, seizure or objection?",
      "hint": "These charges appear on the property certificate.",
      "crit": "eleve",
      "opts": [
        {
          "t": "Yes, free of any charge",
          "s": "ok"
        },
        {
          "t": "No",
          "s": "bad",
          "r": "Have any mortgage/seizure lifted or cleared before buying."
        },
        {
          "t": "I don't know",
          "s": "unk",
          "r": "Check the registrations (mortgage, seizure, objection) on the title."
        }
      ]
    },
    {
      "q": "Do you have the urban agency information note?",
      "hint": "It specifies zoning and building rules.",
      "crit": "bloquant",
      "opts": [
        {
          "t": "Yes",
          "s": "ok"
        },
        {
          "t": "No",
          "s": "bad",
          "r": "Get the urban agency information note: it's essential."
        },
        {
          "t": "I don't know",
          "s": "unk",
          "r": "Request the planning information note before any commitment."
        }
      ]
    },
    {
      "q": "Is the land classified as buildable?",
      "hint": "Check the zoning in the development plan.",
      "crit": "bloquant",
      "opts": [
        {
          "t": "Yes",
          "s": "ok"
        },
        {
          "t": "No / agricultural or green zone",
          "s": "bad",
          "r": "Non-buildable land ruins the project. Confirm the zoning."
        },
        {
          "t": "I don't know",
          "s": "unk",
          "r": "Confirm buildability in the development plan."
        }
      ]
    },
    {
      "q": "Does the land have direct access to a public road?",
      "hint": "Landlocked land is hard to use.",
      "crit": "bloquant",
      "opts": [
        {
          "t": "Yes",
          "s": "ok"
        },
        {
          "t": "No / landlocked",
          "s": "bad",
          "r": "Secure legal access: landlocked land blocks the permit."
        },
        {
          "t": "I don't know",
          "s": "unk",
          "r": "Check for legal access to a public road."
        }
      ]
    },
    {
      "q": "Has the boundary survey been done by a surveyor?",
      "hint": "It confirms the real area and boundaries.",
      "crit": "eleve",
      "opts": [
        {
          "t": "Yes",
          "s": "ok"
        },
        {
          "t": "No",
          "s": "bad",
          "r": "Have the land surveyed: the real area sometimes differs from the title."
        },
        {
          "t": "I don't know",
          "s": "unk",
          "r": "Plan a surveyor's boundary survey before the transaction."
        }
      ]
    },
    {
      "q": "Will payment go through a notary (and not in cash)?",
      "hint": "The notary secures the funds and the deed.",
      "crit": "eleve",
      "opts": [
        {
          "t": "Yes, via notary",
          "s": "ok"
        },
        {
          "t": "No / in cash",
          "s": "bad",
          "r": "Go through a notary: cash exposes you to fraud and a penalty."
        },
        {
          "t": "I don't know",
          "s": "unk",
          "r": "Plan a secure payment via notary, never in cash."
        }
      ]
    }
  ]
};
